spring.application.name=shopping-cart
server.port=8082

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.platform=h2


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console



ibm.mq.queueManager=IMQDESA
ibm.mq.channel=MQ_DEV
ibm.mq.connName=localhost(1414)
ibm.mq.user=dev
ibm.mq.password=dev



#Swagger
springdoc.api-docs.enabled = true
springdoc.swagger-ui.enabled = true
springdoc.swagger-ui.path=/doc/swagger-ui.html

#User Microservice
external.user.api.base-url=${API_USER}
external.stock.api.base-url=${API_STOCK}
jwt.secure.key=${JWT_KEY}